version: "3"

services:
  database-notification:
    image: postgres:alpine
    restart: unless-stopped
    expose:
      - 3132
    ports:
      - "3132:5432"
    volumes:
      - notificationdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=notification_service
  app-notification:
    build:
      context: ./../notification_service # necessary because otherwise docker-compose overrides the context path when merging multiple docker-compose.yml files
      dockerfile: Dockerfile
    restart: always
    container_name: notification_service
    expose:
      - 3100
      - 3101
    ports:
      - "1000:1000"
      - "1001:1001"
    depends_on:
      - database-notification
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-notification:5432/notificationdatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-notification:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "notification_service",
      "--app-port", "1001",
      "--dapr-http-port", "1000",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../notification_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-notification
      - redis
    network_mode: "service:app-notification"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  notificationdata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true
