version: "3"

services:
  database-notification:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./../notification_service/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_CREATE_DB_GAMIFICATION_SERVICE=notification_service
  app-notification:
    build:
      context: ./../notification_service # necessary because otherwise docker-compose overrides the context path when merging multiple docker-compose.yml files
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: notification_service
    expose:
      - 3100
      - 3101
    ports:
      - "3100:3100"
      - "3101:3101"
    depends_on:
      - database-notification
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/notification_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-notification:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "notification_service",
      "--app-port", "3101",
      "--dapr-http-port", "3100",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../notification_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-notification
      - redis
    network_mode: "service:app-notification"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  notificationdata:
  dbdata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true
